module QueryGenerator
  require "singleton"

  # Configuration holder for the whole plugin.
  #
  # You can set/override a configuration value by calling
  #   QueryGenerator::Configuration.set(key, value)
  # Important: This is using a recursive merging function for ruby hashes. Please have a look at the core
  #            extensions
  #
  # Available options:
  #
  # :exclusions
  #   This sets classes and modules which should not be included into the
  #   class linkage graph generated by the DataHolder.
  #   It is a ruby hash with the two keys
  #     :classes and
  #     :modules
  #   which both hold an array of Class / array of Module.
  #
  # :javascript
  #   Options used by the core extensions for some classes, e.g. String, Hash, Array
  #   They are used to convert ruby objects to javascript object strings.
  #   Yes, you could use .to_json, but sometimes this does not produce exactly
  #   what you need.
  #   Available options here:
  #     :indicators -- Array of javascript indicators. If a string starts with one of them, it won't be converted to a javascript string
  #     :end_classes -- Classes which do not contain any more classes to be converted
  #     :container_classes -- Classes which do contain other objects to be converted

  class Configuration
    include Singleton
    include HelperFunctions

    def self.get(config_name)
      self.instance.get(config_name.to_s)
    end

    def self.set(config_name, value)
      self.instance.set(config_name.to_s, value)
    end

    def initialize
      @configuration = {}
    end

    def get(config_name)
      @configuration[config_name] ||= get_default_configuration(config_name)
    end

    def set(config_name, value)
      get(config_name)
      @configuration.recursive_merge!({config_name => value})
    end

    private

    # Provides some default options for the plugin
    #--------------------------------------------------------------
    def get_default_configuration(config_name)
      case config_name.to_s
        when "exclusions"
          {:classes => [], :modules => []}
        when "javascript"
          {:indicators => ["javascript:", "js:", "jQuery(", "$(", "$F("],
           :end_classes => [String, Symbol, Date, DateTime],
           :container_classes => [Array, Hash]}
        else
          {}
      end
    end
  end
end
